"""Remove difficulty from interview questions

Revision ID: 755a962a2c29
Revises: 4e8a1317627f
Create Date: 2026-08-17 11:51:57.106849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '755a962a2c29'
down_revision: Union[str, Sequence[str], None] = '4e8a1317627f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_questions', 'difficulty')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_questions', sa.Column('difficulty', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
