"""Add resume and interview question constraints

Revision ID: a18ee473fdc2
Revises: 68891059d407
Create Date: 2026-08-16 11:53:14.677994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a18ee473fdc2'
down_revision: Union[str, Sequence[str], None] = '68891059d407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_interview_questions_interview_sequence', 'interview_questions', ['interview_id', 'sequence_number'])
    op.create_unique_constraint(None, 'resumes', ['application_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resumes', type_='unique')
    op.drop_constraint('uq_interview_questions_interview_sequence', 'interview_questions', type_='unique')
    # ### end Alembic commands ###
