"""add resume file storage and application uniqueness

Revision ID: c9acfd8a649e
Revises: a7f3c9d21b48
Create Date: 2026-09-03 00:00:00.307554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9acfd8a649e'
down_revision: Union[str, Sequence[str], None] = 'a7f3c9d21b48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_applications_candidate_job_opportunity', 'applications', ['candidate_id', 'job_opportunity_id'])
    op.add_column('resumes', sa.Column('file_data', sa.LargeBinary(), nullable=False))
    op.add_column('resumes', sa.Column('file_size', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'file_size')
    op.drop_column('resumes', 'file_data')
    op.drop_constraint('uq_applications_candidate_job_opportunity', 'applications', type_='unique')
    # ### end Alembic commands ###
