"""Add strengths and weaknesses to candidate evaluations

Revision ID: dd15c0aef907
Revises: ad725728af5d
Create Date: 2026-08-27 14:09:57.195661

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "dd15c0aef907"
down_revision: Union[str, Sequence[str], None] = "ad725728af5d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "candidate_evaluations",
        sa.Column(
            "strengths",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )

    op.add_column(
        "candidate_evaluations",
        sa.Column(
            "weaknesses",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("candidate_evaluations", "weaknesses")
    op.drop_column("candidate_evaluations", "strengths")
    # ### end Alembic commands ###