"""add matching_details column to screening_results

Revision ID: dd87f84c84a9
Revises: 694c6d6a3b95
Create Date: 2026-08-23 12:06:52.708692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd87f84c84a9'
down_revision: Union[str, Sequence[str], None] = '694c6d6a3b95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screening_results', sa.Column('matching_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screening_results', 'matching_details')
    # ### end Alembic commands ###
